CLIENT_APP = 'client'
TRANSACTION_APP = 'transaction'
COMMON_APP = 'common'
COMPANY_APP = 'company'
PTP_APP = 'ptp'
EMPTY_STRING = ''
MAX_TWO = 2
LAST_ITEM = -1
CHAR_0 = '0'
CHAR_DOT = '.'

SIZE_SUB_CODE = 6
SIZE_CUSTOM_CODE = 12
DEFAULT_INDEX = 0
MIN_SIZE = 0
MIN_RANGE = 0
MAX_RANGE = 999999

STR_NULL = 'null'
